# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        revit_config:
          - Release 2019
          - Release 2020
          - Release 2021
          - Release 2022
          - Release 2023
          - Release 2024
          - Release 2025
          - Release 2026

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v5.0.2
      with:
        tag_prefix: "v"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Authenticate nuget feed
      run: dotnet nuget add source --username kristoffer-tungland --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kristoffer-tungland/index.json"
      working-directory: src

    # Build, pack, and push dRofusClient.Revit for each Revit configuration
    - name: Restore dRofusClient.Revit
      run: dotnet restore dRofusClient.Revit/dRofusClient.Revit.csproj --configfile nuget.config
      working-directory: src

    - name: Build dRofusClient.Revit
      run: dotnet build dRofusClient.Revit/dRofusClient.Revit.csproj --no-restore --configuration "${{ matrix.revit_config }}" -p:Version=${{ steps.version.outputs.version }}
      working-directory: src

    - name: Pack dRofusClient.Revit
      run: dotnet pack dRofusClient.Revit/dRofusClient.Revit.csproj --no-build --configuration "${{ matrix.revit_config }}" -p:Version=${{ steps.version.outputs.version }} --output ./nupkgs
      working-directory: src

    - name: Push dRofusClient.Revit to GitHub
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.TOKEN }} --source "github" --skip-duplicate
      working-directory: src

    # Build, pack, and push the other projects (only once, not in matrix)
    - name: Restore, Build, Pack, and Push dRofusClient, dRofusClient.Windows, dRofusClient.WindowsCredentials
      if: matrix.revit_config == 'Release 2019' # Only run once
      run: |
        dotnet restore dRofusClient/dRofusClient.csproj --configfile nuget.config
        dotnet build dRofusClient/dRofusClient.csproj --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version }}
        dotnet pack dRofusClient/dRofusClient.csproj --no-build --configuration Release -p:Version=${{ steps.version.outputs.version }} --output ./nupkgs

        dotnet restore dRofusClient.Windows/dRofusClient.Windows.csproj --configfile nuget.config
        dotnet build dRofusClient.Windows/dRofusClient.Windows.csproj --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version }}
        dotnet pack dRofusClient.Windows/dRofusClient.Windows.csproj --no-build --configuration Release -p:Version=${{ steps.version.outputs.version }} --output ./nupkgs

        dotnet restore dRofusClient.WindowsCredentials/dRofusClient.WindowsCredentials.csproj --configfile nuget.config
        dotnet build dRofusClient.WindowsCredentials/dRofusClient.WindowsCredentials.csproj --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version }}
        dotnet pack dRofusClient.WindowsCredentials/dRofusClient.WindowsCredentials.csproj --no-build --configuration Release -p:Version=${{ steps.version.outputs.version }} --output ./nupkgs

        dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.TOKEN }} --source "github" --skip-duplicate
      working-directory: src